# Generated by Django 5.2.6 on 2025-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_a_meal', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
