# Generated by Django 5.2.6 on 2025-10-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_a_meal', '0004_menuitem_menu_id_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
