# Generated by Django 5.2.6 on 2025-10-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_a_meal', '0005_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
