# Generated by Django 5.2.6 on 2025-10-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_meal_menuitem_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
    ]
