# Generated by Django 5.2.6 on 2025-10-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_meal_options_alter_menuitem_options_and_more'),
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_order_item', to='menu.menuitem'),
        ),
    ]
