# Generated by Django 5.2.6 on 2025-11-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_meal_id'),
        ('order', '0003_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.meal'),
            preserve_default=False,
        ),
    ]
